Add option to generate sarif output for ingestion into GitHub code scanning results
ReFirmLabs/centrifuge-cli pull request #42
Opened 2022-05-31 21:40 UTC by ochimo

2022-06-02 21:20 UTC, eacmen commented
@ochimo please address tests that failed in travis

2022-06-03 13:50 UTC, ochimo commented
@eacmen linter issues fixed - thanks

2022-06-07 03:20 UTC, eacmen commented on centrifuge_cli/main.py
> +@click.option('--outfmt', default='human', help='Output format of command', type=click.Choice(['human', 'json', 'csv', 'sarif']))
sarif output format doesn't make sense for all command types. The other output formats are generic and you can output any result from centrifuge to any format. I would add a `--sarif` option to check-policy versus adding sarif as an option here.

2022-06-07 03:24 UTC, eacmen requested changes
Looks good overall. Just one issue to address with the outfmt sarif not making sense for all cmdlets. Make the requested changes and I'll approve.

2022-06-17 18:45 UTC, eacmen approved these changes
approved

2022-06-19 20:57 UTC, merged